# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180814_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='guest', max_length=100),
        ),
    ]
