# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180814_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_data',
        ),
    ]
